disallowed-methods = [
    { path = "futures::channel::mpsc::unbounded", reason = "does not enforce backpressure" },
    { path = "tokio::sync::mpsc::unbounded_channel", reason = "does not enforce backpressure" },
]
avoid-breaking-exported-api = false
