name: "Validate Python Project (uv)"
description: "Validates a given python uv project"
inputs:
  project-path:
    description: "Path to project to check"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
    - uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba #v6.3.1
      with:
        working-directory: ${{ inputs.project-path }}
        enable-cache: true
        # We want a per-project cache and assume that each one uses 'uv'.
        # Furthermore, the symbolic links in the project causes '**' globs to fail.
        cache-dependency-glob: |
          ${{ inputs.project-path }}/pyproject.toml
          ${{ inputs.project-path }}/uv.lock

    - name: Check formatting
      shell: bash
      run: uv run --frozen ruff format --check .
      working-directory: ${{ inputs.project-path }}

    - name: Linting
      shell: bash
      run: uv run --frozen ruff check .
      working-directory: ${{ inputs.project-path }}

    - name: Check types
      shell: bash
      run: uv run --frozen mypy .
      working-directory: ${{ inputs.project-path }}
