base_url = "https://hypha-space.org"
compile_sass = false
theme = "hypha"
build_search_index = true
taxonomies = [
    {name = "track", feed = false},
]

[search]
index_format = "fuse_javascript"

[markdown]
highlight_code = true
highlight_theme = "one-dark"
extra_syntaxes_and_themes = ["syntaxes"]

render_emoji = true

external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

bottom_footnotes = true

github_alerts = true

[extra]
# Put all your custom variables here
