name: Validate

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: validate-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      # Setup Rust toolchain
      - run: rustup component add llvm-tools-preview

      # Cache dependencies and build artifacts
      - uses: swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
          cache-provider: "github"

      # Add custom matcher for cargo output
      - run: echo "::add-matcher::.github/matcher/cargo.json"

      - name: Check formatting
        run: cargo fmt --check

      - name: Lint
        run: cargo clippy -- -D warnings

      # Run tests with coverage instrumentation
      - name: Test
        run: cargo test
        env:
          RUSTFLAGS: -C instrument-coverage
          LLVM_PROFILE_FILE: test-%p-%m.profraw

      # Convert and upload coverage report
      - run: cargo install --locked grcov
      - run: grcov . -s . --binary-path ./target/debug/  --branch --ignore-not-existing -t lcov -o ./lcov.info
      - name: Upload coverage report
        uses: codecov/codecov-action@ad3126e916f78f00edff4ed0317cf185271ccc2d # v5.4.2
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: true
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - uses: EmbarkStudios/cargo-deny-action@34899fc7ba81ca6268d5947a7a16b4649013fea1 #v2.0.11
        with:
          command: check advisories bans licenses sources
